# Generated by Django 3.2.20 on 2023-10-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diaspora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('area_code', models.CharField(max_length=200)),
                ('area_name', models.CharField(max_length=200)),
                ('center', models.CharField(max_length=200)),
                ('center_code', models.CharField(max_length=200)),
                ('polling_station_code', models.CharField(max_length=200)),
                ('polling_station_name', models.CharField(max_length=200)),
                ('voters', models.CharField(max_length=200)),
            ],
        ),
    ]
