# Generated by Django 3.2.20 on 2023-10-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_county'),
    ]

    operations = [
        migrations.RenameField(
            model_name='county',
            old_name='Code',
            new_name='code',
        ),
    ]
