# Generated by Django 3.2.20 on 2023-10-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_code_county_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_code', models.CharField(max_length=200)),
                ('county_name', models.CharField(max_length=200)),
                ('const_code', models.CharField(max_length=200)),
                ('caw_code', models.CharField(max_length=200)),
                ('center_code', models.CharField(max_length=200)),
                ('polling_station_code', models.CharField(max_length=200)),
                ('voters', models.IntegerField()),
            ],
        ),
    ]
